---
# yamllint disable rule:truthy
name: Self Review Gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    with:
      python-version: "3.x"

  gate:
    name: Self review gate
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    environment: self-review
    steps:
      - run: echo "Manually approve this check to confirm you've reviewed the PR."
